import type { Metadata } from "next";
import "@/styles/global.scss";
import CSSEnhancements from "@/utils/CSSEnhancements";
import Navbar from "@/components/nav/Navbar";
import { navItems } from "@/utils/constants";
import Footer from "@/components/footer/Footer";
import localFont from "next/font/local";
import MouseTrackGradient from "@/components/background/MouseTrackGradient";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import Button from "@/components/global/Button";
import LandingPage from "@/components/landing/LandingPage";

const mFont = localFont({
  src: [{ path: "./fonts/m.ttf", style: "regular" }],
  preload: true,
  variable: "--mFont",
});

const nhFont = localFont({
  src: [
    { path: "./fonts/nh/nhdr.ttf", style: "normal", weight: "400" },
    { path: "./fonts/nh/nhdri.ttf", style: "italic", weight: "400" },
    { path: "./fonts/nh/nhdb.ttf", style: "normal", weight: "600" },
    { path: "./fonts/nh/nhdbi.ttf", style: "italic", weight: "600" },
    { path: "./fonts/nh/nhdl.ttf", style: "normal", weight: "200" },
    { path: "./fonts/nh/nhdli.ttf", style: "italic", weight: "200" },
    { path: "./fonts/nh/nhdm.ttf", style: "normal", weight: "500" },
    { path: "./fonts/nh/nhdmi.ttf", style: "italic", weight: "500" },
    { path: "./fonts/nh/nhdt.ttf", style: "normal", weight: "300" },
    { path: "./fonts/nh/nhdti.ttf", style: "italic", weight: "300" },
    { path: "./fonts/nh/nhdxt.ttf", style: "normal", weight: "20" },
    { path: "./fonts/nh/nhdxti.ttf", style: "italic", weight: "200" },
    { path: "./fonts/nh/nhdxxt.ttf", style: "normal", weight: "100" },
    { path: "./fonts/nh/nhdxxti.ttf", style: "italic", weight: "100" },
  ],
  preload: true,
  variable: "--nhFont",
});

const hvFont = localFont({
  src: [
    {
      path: "./fonts/hv/hv.ttf",
      style: "normal",
    },
  ],
  preload: true,
  variable: "--hvFont",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${nhFont.variable} ${hvFont.variable} ${mFont.variable}`}
    >
      <body>
        <MouseTrackGradient />
        <CSSEnhancements />
        <Navbar navItems={navItems} />
        {children}
        <Footer pages={navItems} />
        {draftMode().isEnabled ? <VisualEditing /> : null}
        {draftMode().isEnabled ? (
          <div className="disable-preview__wrapper">
            <p>You are viewing a preview version of this site</p>
            <Button slug="/api/draft-mode/disable">Disable preview mode</Button>
          </div>
        ) : null}
        {draftMode().isEnabled === false ? <LandingPage /> : null}
      </body>
    </html>
  );
}
